[theme]
base = "light"
primaryColor = "#16212C"
backgroundColor = "#F3F5F7"
secondaryBackgroundColor = "#E8ECF0"
textColor = "#16212C"
font = "sans serif"

[server]
maxUploadSize = 15

[browser]
gatherUsageStats = false
